s=str(input("ingrese una letra:"))
a=list("hola mundo")
b=tuple("hola mundo")
c=set("hola mundo")
print(a)
print(b)
print(c)
print("pertenecia de tuplas:",s in a)
print("contaremos cuantas letras o existen en la lista:",a.count("o"))
x=c.copy()
print("la copia del set:",x)
y=a.reverse()
print("la lista invertida",y)
w=b*3
print("la tupla multiplicada:",w)
c.clear()
print("eleminaremos todos los elemtos del set:",c)