#1:creacion
print("creacion")
a=(12,)
b=tuple("hola")
c=tuple(range(0,11))
d=(1,2,3,4)
e=tuple("hoy es el gran dia ")
f=("naranja","mango","uva","higo")
g=("lun","mar","mie","jue","vie")
h=tuple(range(0,20,2))
i=tuple("hola mundo")
j=()
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(h)
print(i)

#2:pertenecia
print("pertenecia")
a=tuple("hola a todos")
b=tuple(range(1,21))
c=("hola","buenas""noches")
d=(1,1,2,3,4,5,5,6)
e=tuple(range(0,21,2))
f=("ene","feb","mar","abr","may")
g=("lun","mar","mie","jue","vie")
h=tuple("los dias de la semana son 7")
i=tuple("los dias")
j=tuple(range(0,101,10))
print("a" in a)
print("hola"not in b)
print(20 in c)
print(2 not in d)
print(3 in e)
print("ene" in f)
print("feb" not in g)
print("l" in h)
print("los" in i)
print(100 not in j)
#3:concatenacion
print("concatenacion ")
a=tuple("los dias son")
b=("lun","mar","mie","jue","vie","sab","dom")
d=tuple(range(0,11))
e=tuple(range(1,12,2))
f=tuple("a caballo regalado no se les mira los dientes")
g=tuple("refran")
h=tuple("hola mundo")
i=("uva","pera","naranja","higo")
j=tuple("las frutas son ")
print(a+b)
print(c+d)
print(e+f)
print(g+h)
print(i+a)
print(a+i)
print(b+d)
print(a+j)
print(e+a)
print(a+b+g)
#comparacion
print("comparacion ")
a=tuple("los dias son")
b=("lun","mar","mie","jue","vie","sab","dom")
d=tuple(range(0,11))
e=tuple(range(1,12,2))
f=tuple("a caballo regalado no se les mira los dientes")
g=tuple("hoy es el gran dia ")
h=("naranja","mango","uva","higo")
i=("lun","mar","mie","jue","vie")
c=tuple(range(0,20,2))

print(a==b)
print(b>a)
print(d<e)
print(d>e)
print(f==g)
print(f<g)
print(h>i)
print(h<i)
print(i==j)
print(h<i)
#indexacion
print("indexacion")
a=(12,)
b=tuple("hola")
c=tuple(range(0,11))
d=(1,2,3,4)
e=tuple("hoy es el gran dia ")
f=("naranja","mango","uva","higo")
g=("lun","mar","mie","jue","vie")
h=("naranja","mango","uva","higo")
i=("lun","mar","mie","jue","vie")
print(a[0])
print(c[2])
print(b[1])
print(d[0])
print(e[0:5:2])
print(f[0:3:2])
print(g[3])
print(h[1:4:2])
print(i[2])
#cortado:
print("cortado")
a = ("lunes", "martes", "miercoles", "jueves", "viernes", "sabado")
b=(1,2,3,4)
c=tuple(range(0,10))
d=("hola")
e=tuple(" a todos")
f=tuple(range(0,13,2))
g=("ene","feb","mar")
h=tuple("los planetas son ")
i=tuple(range(1,12))
j=tuple(" dias de la semana son")
print(a[0:2])
print(b[0:3:2])
print(c[3:6:3])
print(d[1])
print(e[0:5:3])
print(f[0:2])
print(g[0:3])
print(h[0:6:2])
print(i[4:1:-2])
print(j[0:9:2])
#longitud0
print("longitud")
a=(12,)
b=tuple("hola")
c=tuple(range(0,11))
d=(1,2,3,4)
e=tuple("hoy es el gran dia ")
f=("naranja","mango","uva","higo")
g=("lun","mar","mie","jue","vie")
h=tuple(range(0,20,2))
i=tuple("hola mundo")
j=()
print(len(a))
print(len(b))
print(len(a+b))
print(len(d))
print(len(c))
print(len(d+e+a))
print(len(j))
print(len(g))
print(len(h))
print(len(f))
#iteracion
print("iteracion")
a=tuple("los dias son")
b=("lun","mar","mie","jue","vie","sab","dom")
d=tuple(range(0,11))
e=tuple(range(1,12,2))
f=tuple("a caballo regalado no se les mira los dientes")
g=tuple("hoy es el gran dia ")
h=("naranja","mango","uva","higo")
i=("lun","mar","mie","jue","vie")
c=tuple(range(0,20,2))
for j in a:
    print(j)
for k in (b+a):
    print(k)
for l in c:
    print(l)
for m in d:
    print(m)
for n in (i+c):
    print(n)
for ñ in g:
    print(ñ)
for o in f:
    print(o)
for p in (f+g):
    print(p)
for q in (c+a):
    print(q)
for r in (f+a):
    print(r)
#busquedad:
print("busquedad")
a=tuple("los dias son")
b=("lun","mar","mie","jue","vie","sab","dom")
d=tuple(range(0,11))
e=tuple(range(1,12,2))
f=tuple("a caballo regalado no se les mira los dientes")
g=tuple("hoy es el gran dia ")
h=("naranja","mango","uva","higo")
i=("lun","mar","mie","jue","vie")
c=tuple(range(0,20,2))
print(a.index("o"))
print(b.index("mie"))
print(c.index(4))
print(d.index(6))
print(e.index(3))
print(f.index("c"))
print(g.index("h"))
print(i.index("jue"))
#conteo
print("conteo")
a = ("lunes", "martes", "miercoles", "jueves", "viernes", "sabado")
b=(1,2,3,4)
c=tuple(range(0,10))
d=("hola")
e=tuple(" a todos")
f=tuple(range(0,13,2))
g=("ene","feb","mar")
h=tuple("los planetas son ")
i=tuple(range(1,12))
j=tuple(" dias de la semana son")
print(a.count("lunes"))
print(b.count(3))
print(d.count("hola"))
print(e.count("o"))
print(c.count(14))
print(f.count(15))
print(g.count("ene"))
print(h.count("o"))
print(i.count(1))
print(j.count("a"))
#max y min
print("maximos y minimos")
a=tuple(range(0,11))
b=(1,2,3,4)
c=(1,2,3,4,666,6,7,7,8,9,8,7,7,6,6,6,6,6,67,777777,7,7,7,7,7)
d=tuple(range(0,12,2))
e=tuple(range(0,100))
f=(33343,12344.98768,958676)
g=tuple(range(0,1000,10))
h=tuple(range(0,200,7))
i=tuple(range(34,400,8))
j=tuple(range(200,1000,45))
print(max(a))
print(max(b))
print(max(c))
print(max(d))
print(max(e))
print(min(f))
print(min(g))
print(min(h))
print(min(i))
print(min(j))
#multipliacion de tuplas
print("multiplicacion")
a=(12,)
b=tuple("hola")
c=tuple(range(0,11))
d=(1,2,3,4)
e=tuple("hoy es el gran dia ")
f=("naranja","mango","uva","higo")
g=("lun","mar","mie","jue","vie")
h=tuple(range(0,20,2))
i=tuple("hola mundo")
j=()
print(a*4)
print(b*2)
print(b+c*2)
print(e*2)
print(f*3)
print(g*2+h*2)
print(i*5)
print(j*2)
print(a*3)
print(i*2)
#clonado:
print("clonado")
a=(12,)
b=tuple("hola")
c=tuple(range(0,11))
d=(1,2,3,4)
e=tuple("hoy es el gran dia ")
f=("naranja","mango","uva","higo")
g=("lun","mar","mie","jue","vie")
h=("naranja","mango","uva","higo")
i=("lun","mar","mie","jue","vie")
print(a[:])
print(b[:])
print(c[:])
print(d[:])
print(e[:])
print(f[:])
print(g[:])
print(h[:])
print(i[:])
print(j[:])

